baseURL = 'https://ruiss3au.github.io/'
languageCode = 'en-us'
title = 'ruiss3au'
theme = 'ruiss3au'

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = 'monokai'

enableRobotsTXT = true

[params]
  description = "Analysis of 3GPP standardization and 5G/6G telecommunications, plus notes on Linux, low-level programming, computers, and exploit development."
  author = "ruiss3au"
  mainSections = ["posts"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5

[privacy]
  [privacy.youtube]
    privacyEnhanced = true
